"""Add deployment_config table

Revision ID: add_deployment_config
Revises: add_sales_order_result_table
Create Date: 2024-01-20 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_deployment_config'
down_revision = 'add_sales_order_result'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_config',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('environment_variables', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['fireflies.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cin7_uploader'
    )
    op.create_index(op.f('ix_cin7_uploader_deployment_config_created_by'), 'deployment_config', ['created_by'], unique=False, schema='cin7_uploader')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cin7_uploader_deployment_config_created_by'), table_name='deployment_config', schema='cin7_uploader')
    op.drop_table('deployment_config', schema='cin7_uploader')
    # ### end Alembic commands ###

