"""Initial migration: create cin7_uploader schema and tables

Revision ID: fa1f6ce1b016
Revises: 
Create Date: 2025-12-18 14:56:14.394902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa1f6ce1b016'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Create schema if it doesn't exist
    op.execute("CREATE SCHEMA IF NOT EXISTS cin7_uploader")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cin7_uploader'
    )
    # Note: fireflies.users table already exists, we just reference it via foreign keys
    # No need to create it here
    
    op.create_table('client_cin7_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('application_key', sa.Text(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['cin7_uploader.client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cin7_uploader'
    )
    with op.batch_alter_table('client_cin7_credentials', schema='cin7_uploader') as batch_op:
        batch_op.create_index(batch_op.f('ix_cin7_uploader_client_cin7_credentials_client_id'), ['client_id'], unique=True)

    op.create_table('client_csv_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('mapping_name', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('column_mapping', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['cin7_uploader.client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'mapping_name', name='client_csv_mapping_client_name_unique'),
    schema='cin7_uploader'
    )
    with op.batch_alter_table('client_csv_mapping', schema='cin7_uploader') as batch_op:
        batch_op.create_index(batch_op.f('ix_cin7_uploader_client_csv_mapping_client_id'), ['client_id'], unique=False)

    op.create_table('client_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('default_status', sa.String(length=50), nullable=False),
    sa.Column('default_location', sa.UUID(), nullable=True),
    sa.Column('default_currency', sa.String(length=10), nullable=False),
    sa.Column('tax_inclusive', sa.Boolean(), nullable=False),
    sa.Column('auto_fulfill', sa.Boolean(), nullable=False),
    sa.Column('default_fulfillment_status', sa.String(length=50), nullable=True),
    sa.Column('require_customer_reference', sa.Boolean(), nullable=False),
    sa.Column('require_invoice_number', sa.Boolean(), nullable=False),
    sa.Column('date_format', sa.String(length=50), nullable=False),
    sa.Column('default_delay_between_orders', sa.Float(), nullable=False),
    sa.Column('default_batch_size', sa.Integer(), nullable=False),
    sa.Column('default_batch_delay', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['cin7_uploader.client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cin7_uploader'
    )
    with op.batch_alter_table('client_settings', schema='cin7_uploader') as batch_op:
        batch_op.create_index(batch_op.f('ix_cin7_uploader_client_settings_client_id'), ['client_id'], unique=True)

    op.create_table('sales_order_upload',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('successful_orders', sa.Integer(), nullable=False),
    sa.Column('failed_orders', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['cin7_uploader.client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['fireflies.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cin7_uploader'
    )
    with op.batch_alter_table('sales_order_upload', schema='cin7_uploader') as batch_op:
        batch_op.create_index(batch_op.f('ix_cin7_uploader_sales_order_upload_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cin7_uploader_sales_order_upload_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cin7_uploader_sales_order_upload_user_id'), ['user_id'], unique=False)

    op.create_table('user_client',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['cin7_uploader.client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['fireflies.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='user_client_user_client_unique'),
    schema='cin7_uploader'
    )
    with op.batch_alter_table('user_client', schema='cin7_uploader') as batch_op:
        batch_op.create_index(batch_op.f('ix_cin7_uploader_user_client_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cin7_uploader_user_client_user_id'), ['user_id'], unique=False)

    # Note: Removed table drops for tables we don't own (test, echo_update, integration_settings)
    # These are from other parts of the database and shouldn't be managed by this migration
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed table recreations for tables we don't own
    with op.batch_alter_table('user_client', schema='cin7_uploader') as batch_op:
        batch_op.drop_index(batch_op.f('ix_cin7_uploader_user_client_user_id'))
        batch_op.drop_index(batch_op.f('ix_cin7_uploader_user_client_client_id'))

    op.drop_table('user_client', schema='cin7_uploader')
    with op.batch_alter_table('sales_order_upload', schema='cin7_uploader') as batch_op:
        batch_op.drop_index(batch_op.f('ix_cin7_uploader_sales_order_upload_user_id'))
        batch_op.drop_index(batch_op.f('ix_cin7_uploader_sales_order_upload_created_at'))
        batch_op.drop_index(batch_op.f('ix_cin7_uploader_sales_order_upload_client_id'))

    op.drop_table('sales_order_upload', schema='cin7_uploader')
    with op.batch_alter_table('client_settings', schema='cin7_uploader') as batch_op:
        batch_op.drop_index(batch_op.f('ix_cin7_uploader_client_settings_client_id'))

    op.drop_table('client_settings', schema='cin7_uploader')
    with op.batch_alter_table('client_csv_mapping', schema='cin7_uploader') as batch_op:
        batch_op.drop_index(batch_op.f('ix_cin7_uploader_client_csv_mapping_client_id'))

    op.drop_table('client_csv_mapping', schema='cin7_uploader')
    with op.batch_alter_table('client_cin7_credentials', schema='cin7_uploader') as batch_op:
        batch_op.drop_index(batch_op.f('ix_cin7_uploader_client_cin7_credentials_client_id'))

    op.drop_table('client_cin7_credentials', schema='cin7_uploader')
    # Note: fireflies.users table is not dropped - it's shared with fireflies-tasks
    op.drop_table('client', schema='cin7_uploader')
    
    # Optionally drop schema (commented out to be safe)
    # op.execute("DROP SCHEMA IF EXISTS cin7_uploader CASCADE")
    # ### end Alembic commands ###
